on:
  push:
    branches:
      - main
      - testing

name: Building V8

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} / v8-r-${{ matrix.version }}-${{ matrix.pkgver }}

    strategy:
      fail-fast: false
      matrix:
        distro: [ 'arch' ]
        version: [ '12.4.245' ]
        pkgver: [ '1' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          docker build ${{ matrix.distro }} -t mybuild

      - name: copy
        run: |
          docker run -d --name myrun mybuild
          docker cp myrun:/home/archie/v8-r/v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.tar.zst .
          docker cp myrun:/home/archie/v8-r/v8-r.sha256sum ./v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.sha256sum
          docker stop myrun

      - name: store
        uses: actions/upload-artifact@v4
        with:
          name: v8-r-${{ matrix.version }}-${{ matrix.pkgver }}
          path: | 
            v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.*
 
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ matrix.version }}-${{ matrix.pkgver }}
          name: Release ${{ matrix.version }}-${{ matrix.pkgver }}
          draft: false
          prerelease: false
          files: |
            v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.tar.zst
            v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.sha256sum

