on:
  push:
    branches:
      - master

name: Building V8

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} / v8-r-${{ matrix.version }}-${{ matrix.pkgver }}

    strategy:
      fail-fast: false
      matrix:
        distro: [ 'arch' ]
        version: [ '8.8.243' ]
        pkgver: [ '1' ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          docker build ${{ matrix.distro }} -t mybuild

      - name: copy
        run: |
          docker run -d --name myrun mybuild
          docker cp myrun:/home/archie/v8-r/v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.tar.zst .
          docker stop myrun

      - name: store
        uses: actions/upload-artifact@v2
        with:
          name: v8-r-${{ matrix.version }}-${{ matrix.pkgver }}
          path: v8-r-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.tar.zst
